import os
import sys
from github import Github
from huggingface_hub import InferenceClient

def main():
    # 1. Fetch environment variables injected by GitHub Actions
    github_token = os.getenv("INPUT_GITHUB_TOKEN")
    hf_token = os.getenv("INPUT_HF_TOKEN")
    repository_name = os.getenv("GITHUB_REPOSITORY")
    pr_number = os.getenv("INPUT_PR_NUMBER")

    if not github_token or not hf_token or not repository_name or not pr_number:
        print("❌ Error: Missing required environment variables.")
        sys.exit(1)

    print(f"🚀 Initializing Hugging Face Summarizer for {repository_name} PR #{pr_number}...")

    # 2. Authenticate GitHub and extract the PR Diff
    try:
        g = Github(github_token)
        repo = g.get_repo(repository_name)
        pr = repo.get_pull(int(pr_number))
        
        diffs = pr.get_files()
        diff_text = ""
        for file in diffs:
            diff_text += f"File: {file.filename}\n{file.patch}\n\n"
            # Protect LLM context limits on mega pull requests
            if len(diff_text) > 30000:
                diff_text += "... [Diff truncated for size limit] ..."
                break
    except Exception as e:
        print(f"❌ Failed to fetch PR data from GitHub: {e}")
        sys.exit(1)

    # 3. Connect to Hugging Face Serverless API and generate summary
    try:
        # Utilizing an ultra-fast, free text-generation model
        client = InferenceClient(api_key=hf_token)
        
        prompt = f"""You are an expert code reviewer. Analyze the following GitHub Pull Request diff and provide a concise summary.
Your response MUST be exactly 3 bullet points. Focus on:
1. What main feature/fix was introduced.
2. Which critical files or architectural components were changed.
3. Any potential risks or things reviewers should pay extra attention to.

PR Diff:
{diff_text}

Summary:"""

        messages = [{"role": "user", "content": prompt}]
        
        # Pulling from the default fastest open-weights model provider stack
        completion = client.chat.completions.create(
            model="meta-llama/Meta-Llama-3-8B-Instruct", 
            messages=messages, 
            max_tokens=500
        )
        summary = completion.choices[0].message.content
    except Exception as e:
        print(f"❌ Failed to generate summary from Hugging Face: {e}")
        sys.exit(1)

    # 4. Post the generated summary back to your PR as a comment
    try:
        comment_body = f"### 🤖 AI Pull Request Summary (via Hugging Face)\n\n{summary}\n\n*_Generated by Serverless Llama-3-8B_*"
        pr.create_issue_comment(comment_body)
        print("✅ Summary successfully posted to the PR!")
    except Exception as e:
        print(f"❌ Failed to post comment to PR: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
